// <auto-generated />
using System;
using BlotzTask.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlotzTask.Migrations
{
    [DbContext(typeof(BlotzTaskDbContext))]
    partial class BlotzTaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlotzTask.Modules.AiUsage.Entities.AiUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InputTokens")
                        .HasColumnType("int");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("int");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("AiUsageRecords");
                });

            modelBuilder.Entity("BlotzTask.Modules.AiUsage.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MonthlyTokenLimit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MonthlyTokenLimit = 300000,
                            Name = "Free"
                        },
                        new
                        {
                            Id = 2,
                            MonthlyTokenLimit = 3000000,
                            Name = "Pro"
                        });
                });

            modelBuilder.Entity("BlotzTask.Modules.AiUsage.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSubscriptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2025, 9, 9, 14, 34, 27, 575, DateTimeKind.Utc),
                            PlanId = 1,
                            UserId = new Guid("718ccb8f-ce52-4e51-8cfe-2a44cdca77d1")
                        });
                });

            modelBuilder.Entity("BlotzTask.Modules.Badges.Domain.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DescriptionZh")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameZh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Badges", (string)null);
                });

            modelBuilder.Entity("BlotzTask.Modules.Badges.Domain.BadgeCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<string>("ConditionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConditionOperator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("ConditionValue")
                        .HasColumnType("float");

                    b.Property<string>("TriggerAction")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.ToTable("BadgeCriteria", (string)null);
                });

            modelBuilder.Entity("BlotzTask.Modules.Badges.Domain.UserBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EarnedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique();

                    b.ToTable("UserBadges", (string)null);
                });

            modelBuilder.Entity("BlotzTask.Modules.Badges.Domain.UserProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("UserId");

                    b.ToTable("UserProgress", (string)null);
                });

            modelBuilder.Entity("BlotzTask.Modules.Labels.Domain.Label", b =>
                {
                    b.Property<int>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabelId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LabelId");

                    b.HasIndex("UserId");

                    b.ToTable("Labels", null, t =>
                        {
                            t.HasCheckConstraint("CK_Label_Scope_User", "(Scope = 'Global' AND UserId IS NULL) OR (Scope = 'Custom' AND UserId IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            LabelId = 6,
                            Color = "#c2e49f",
                            Description = "Work related tasks",
                            Name = "Work",
                            Scope = "Global"
                        },
                        new
                        {
                            LabelId = 7,
                            Color = "#cce7db",
                            Description = "Life related tasks",
                            Name = "Life",
                            Scope = "Global"
                        },
                        new
                        {
                            LabelId = 8,
                            Color = "#d6faf9",
                            Description = "Learning related tasks",
                            Name = "Learning",
                            Scope = "Global"
                        },
                        new
                        {
                            LabelId = 9,
                            Color = "#bad5fa",
                            Description = "Health related tasks",
                            Name = "Health",
                            Scope = "Global"
                        });
                });

            modelBuilder.Entity("BlotzTask.Modules.Notes.Domain.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPersistent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("BlotzTask.Modules.Pomodoro.Domain.PomodoroSetting", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCountdown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Sound")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Timing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(25);

                    b.HasKey("UserId");

                    b.ToTable("PomodoroSettings", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("718ccb8f-ce52-4e51-8cfe-2a44cdca77d1"),
                            IsCountdown = false,
                            Timing = 25
                        });
                });

            modelBuilder.Entity("BlotzTask.Modules.Reviews.Domain.ReviewReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiGeneratedLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiInputJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AiInputTaskCount")
                        .HasColumnType("int");

                    b.Property<string>("AiModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("PeriodEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("PeriodStartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PeriodType", "PeriodStartUtc")
                        .IsUnique();

                    b.ToTable("ReviewReports", (string)null);
                });

            modelBuilder.Entity("BlotzTask.Modules.Tasks.Domain.Entities.DeletedTaskItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<int?>("LabelId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TimeType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LabelId");

                    b.HasIndex("UserId");

                    b.ToTable("DeletedTaskItems", t =>
                        {
                            t.HasCheckConstraint("CK_DeletedTaskItem_SingleTime_Equals", "([TimeType] IS NULL) OR ([TimeType] <> 0) OR ([StartTime] = [EndTime])");

                            t.HasCheckConstraint("CK_DeletedTaskItem_Start_Before_Or_Equal_End", "([StartTime] IS NULL AND [EndTime] IS NULL) OR ([StartTime] <= [EndTime])");

                            t.HasCheckConstraint("CK_DeletedTaskItem_Time_Valid", "(  ([TimeType] IS NULL AND [StartTime] IS NULL AND [EndTime] IS NULL)   OR  ([TimeType] IS NOT NULL AND [StartTime] IS NOT NULL AND [EndTime] IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("BlotzTask.Modules.Tasks.Domain.Entities.RecurringOccurrenceOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("OccurrenceDate")
                        .HasColumnType("date");

                    b.Property<int>("OverrideType")
                        .HasColumnType("int");

                    b.Property<int>("RecurringTaskId")
                        .HasColumnType("int");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.HasIndex("RecurringTaskId", "OccurrenceDate")
                        .IsUnique();

                    b.ToTable("RecurringOccurrenceOverrides", (string)null);
                });

            modelBuilder.Entity("BlotzTask.Modules.Tasks.Domain.Entities.RecurringTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("DeadlineOffsetDays")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("DeadlineTimeOfDay")
                        .HasColumnType("time");

                    b.Property<string>("DeadlineTimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeadline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("LabelId")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousRecurringTaskId")
                        .HasColumnType("int");

                    b.Property<string>("ScheduleTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("TemplateEndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("TemplateStartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TimeType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LabelId");

                    b.HasIndex("PreviousRecurringTaskId");

                    b.HasIndex("UserId", "IsActive");

                    b.HasIndex("SeriesId", "StartDate", "EndDate");

                    b.ToTable("RecurringTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecurringTask_Deadline_Offset_NonNegative", "([DeadlineOffsetDays] IS NULL OR [DeadlineOffsetDays] >= 0)");
                        });
                });

            modelBuilder.Entity("BlotzTask.Modules.Tasks.Domain.Entities.RecurringTaskSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsDeleted");

                    b.ToTable("RecurringTaskSeries", (string)null);
                });

            modelBuilder.Entity("BlotzTask.Modules.Tasks.Domain.Entities.Subtask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("ParentTaskId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ParentTaskId");

                    b.ToTable("Subtasks", (string)null);
                });

            modelBuilder.Entity("BlotzTask.Modules.Tasks.Domain.Entities.TaskDeadline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("DueAt");

                    b.HasIndex("TaskItemId")
                        .IsUnique();

                    b.HasIndex("IsPinned", "DueAt");

                    b.ToTable("TaskDeadlines", (string)null);
                });

            modelBuilder.Entity("BlotzTask.Modules.Tasks.Domain.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AlertTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<int?>("LabelId")
                        .HasColumnType("int");

                    b.Property<string>("NotificationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecurringOccurrenceOverrideId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TimeType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LabelId");

                    b.HasIndex("RecurringOccurrenceOverrideId")
                        .IsUnique()
                        .HasFilter("[RecurringOccurrenceOverrideId] IS NOT NULL");

                    b.HasIndex("UserId", "StartTime", "EndTime");

                    b.ToTable("TaskItems", t =>
                        {
                            t.HasCheckConstraint("CK_TaskItem_SingleTime_Equals", "([TimeType] IS NULL) OR ([TimeType] <> 0) OR ([StartTime] = [EndTime])");

                            t.HasCheckConstraint("CK_TaskItem_Start_Before_Or_Equal_End", "([StartTime] IS NULL AND [EndTime] IS NULL) OR ([StartTime] <= [EndTime])");

                            t.HasCheckConstraint("CK_TaskItem_Time_Valid", "(  ([TimeType] IS NULL AND [StartTime] IS NULL AND [EndTime] IS NULL)   OR  ([TimeType] IS NOT NULL AND [StartTime] IS NOT NULL AND [EndTime] IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("BlotzTask.Modules.Users.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnboarded")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SignUpAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Timezone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Auth0UserId")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("718ccb8f-ce52-4e51-8cfe-2a44cdca77d1"),
                            Auth0UserId = "auth0|68c03ab7a093c0727999a791",
                            CreationAt = new DateTime(2025, 9, 9, 14, 34, 27, 575, DateTimeKind.Utc),
                            DisplayName = "blotztest1@gmail.com",
                            Email = "blotztest1@gmail.com",
                            IsOnboarded = false,
                            LoginAt = new DateTime(2025, 9, 9, 14, 34, 27, 575, DateTimeKind.Utc),
                            PictureUrl = "https://s.gravatar.com/avatar/d7eee1179900d1154cf2b3a64f7f91dd?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fbl.png",
                            SignUpAt = new DateTime(2025, 9, 9, 14, 33, 27, 955, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 9, 9, 14, 34, 27, 575, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BlotzTask.Modules.Users.Domain.UserPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoRollover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("DailyPlanningNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EveningWrapUpNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("OverdueNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("En");

                    b.Property<bool>("UpcomingNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("718ccb8f-ce52-4e51-8cfe-2a44cdca77d1"),
                            AutoRollover = true,
                            DailyPlanningNotification = false,
                            EveningWrapUpNotification = false,
                            OverdueNotification = true,
                            PreferredLanguage = "Zh",
                            UpcomingNotification = true
                        });
                });

            modelBuilder.Entity("BlotzTask.Modules.Users.Domain.UserPushToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserPushTokens", (string)null);
                });

            modelBuilder.Entity("BlotzTask.Modules.AiUsage.Entities.AiUsageRecord", b =>
                {
                    b.HasOne("BlotzTask.Modules.Users.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlotzTask.Modules.AiUsage.Entities.UserSubscription", b =>
                {
                    b.HasOne("BlotzTask.Modules.AiUsage.Entities.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlotzTask.Modules.Users.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlotzTask.Modules.Badges.Domain.BadgeCriteria", b =>
                {
                    b.HasOne("BlotzTask.Modules.Badges.Domain.Badge", "Badge")
                        .WithMany("Criteria")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("BlotzTask.Modules.Badges.Domain.UserBadge", b =>
                {
                    b.HasOne("BlotzTask.Modules.Badges.Domain.Badge", null)
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlotzTask.Modules.Users.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlotzTask.Modules.Badges.Domain.UserProgress", b =>
                {
                    b.HasOne("BlotzTask.Modules.Users.Domain.AppUser", null)
                        .WithOne()
                        .HasForeignKey("BlotzTask.Modules.Badges.Domain.UserProgress", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlotzTask.Modules.Labels.Domain.Label", b =>
                {
                    b.HasOne("BlotzTask.Modules.Users.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlotzTask.Modules.Notes.Domain.Note", b =>
                {
                    b.HasOne("BlotzTask.Modules.Users.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlotzTask.Modules.Pomodoro.Domain.PomodoroSetting", b =>
                {
                    b.HasOne("BlotzTask.Modules.Users.Domain.AppUser", "User")
                        .WithOne("PomodoroSetting")
                        .HasForeignKey("BlotzTask.Modules.Pomodoro.Domain.PomodoroSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlotzTask.Modules.Reviews.Domain.ReviewReport", b =>
                {
                    b.HasOne("BlotzTask.Modules.Users.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlotzTask.Modules.Tasks.Domain.Entities.DeletedTaskItem", b =>
                {
                    b.HasOne("BlotzTask.Modules.Labels.Domain.Label", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId");

                    b.HasOne("BlotzTask.Modules.Users.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Label");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlotzTask.Modules.Tasks.Domain.Entities.RecurringOccurrenceOverride", b =>
                {
                    b.HasOne("BlotzTask.Modules.Tasks.Domain.Entities.RecurringTask", "RecurringTask")
                        .WithMany()
                        .HasForeignKey("RecurringTaskId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BlotzTask.Modules.Tasks.Domain.Entities.RecurringTaskSeries", "Series")
                        .WithMany("Overrides")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecurringTask");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("BlotzTask.Modules.Tasks.Domain.Entities.RecurringTask", b =>
                {
                    b.HasOne("BlotzTask.Modules.Labels.Domain.Label", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId");

                    b.HasOne("BlotzTask.Modules.Tasks.Domain.Entities.RecurringTask", "PreviousRecurringTask")
                        .WithMany()
                        .HasForeignKey("PreviousRecurringTaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BlotzTask.Modules.Tasks.Domain.Entities.RecurringTaskSeries", "Series")
                        .WithMany("Versions")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BlotzTask.Modules.Users.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BlotzTask.Modules.Tasks.Domain.Entities.RecurrencePattern", "Pattern", b1 =>
                        {
                            b1.Property<int>("RecurringTaskId")
                                .HasColumnType("int");

                            b1.Property<int?>("DayOfMonth")
                                .HasColumnType("int")
                                .HasColumnName("DayOfMonth");

                            b1.Property<int?>("DaysOfWeek")
                                .HasColumnType("int")
                                .HasColumnName("DaysOfWeek");

                            b1.Property<int>("Frequency")
                                .HasColumnType("int")
                                .HasColumnName("Frequency");

                            b1.Property<int>("Interval")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(1)
                                .HasColumnName("Interval");

                            b1.HasKey("RecurringTaskId");

                            b1.ToTable("RecurringTasks");

                            b1.WithOwner()
                                .HasForeignKey("RecurringTaskId");
                        });

                    b.Navigation("Label");

                    b.Navigation("Pattern")
                        .IsRequired();

                    b.Navigation("PreviousRecurringTask");

                    b.Navigation("Series");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlotzTask.Modules.Tasks.Domain.Entities.RecurringTaskSeries", b =>
                {
                    b.HasOne("BlotzTask.Modules.Users.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlotzTask.Modules.Tasks.Domain.Entities.Subtask", b =>
                {
                    b.HasOne("BlotzTask.Modules.Tasks.Domain.Entities.TaskItem", "ParentTask")
                        .WithMany("Subtasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentTask");
                });

            modelBuilder.Entity("BlotzTask.Modules.Tasks.Domain.Entities.TaskDeadline", b =>
                {
                    b.HasOne("BlotzTask.Modules.Tasks.Domain.Entities.TaskItem", "TaskItem")
                        .WithOne("Deadline")
                        .HasForeignKey("BlotzTask.Modules.Tasks.Domain.Entities.TaskDeadline", "TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("BlotzTask.Modules.Tasks.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("BlotzTask.Modules.Labels.Domain.Label", "Label")
                        .WithMany("TaskItems")
                        .HasForeignKey("LabelId");

                    b.HasOne("BlotzTask.Modules.Tasks.Domain.Entities.RecurringOccurrenceOverride", "RecurringOccurrenceOverride")
                        .WithOne("TaskItem")
                        .HasForeignKey("BlotzTask.Modules.Tasks.Domain.Entities.TaskItem", "RecurringOccurrenceOverrideId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BlotzTask.Modules.Users.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Label");

                    b.Navigation("RecurringOccurrenceOverride");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlotzTask.Modules.Users.Domain.UserPreference", b =>
                {
                    b.HasOne("BlotzTask.Modules.Users.Domain.AppUser", null)
                        .WithOne()
                        .HasForeignKey("BlotzTask.Modules.Users.Domain.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlotzTask.Modules.Users.Domain.UserPushToken", b =>
                {
                    b.HasOne("BlotzTask.Modules.Users.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlotzTask.Modules.Badges.Domain.Badge", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("BlotzTask.Modules.Labels.Domain.Label", b =>
                {
                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("BlotzTask.Modules.Tasks.Domain.Entities.RecurringOccurrenceOverride", b =>
                {
                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("BlotzTask.Modules.Tasks.Domain.Entities.RecurringTaskSeries", b =>
                {
                    b.Navigation("Overrides");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("BlotzTask.Modules.Tasks.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("Deadline");

                    b.Navigation("Subtasks");
                });

            modelBuilder.Entity("BlotzTask.Modules.Users.Domain.AppUser", b =>
                {
                    b.Navigation("PomodoroSetting")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
