name: Build, test and run mobileui

on:
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize

jobs:
  build-and-test-mobile-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: ./blotztask-mobile

      - name: Run ESLint on mobile
        run: npx eslint . --ext .ts,.tsx,.js
        working-directory: ./blotztask-mobile
