name: Staging - Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - fix-frontend-staging-deploy  
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.APP_PUBLISH_PROFILE }}
  WEBAPP_NAME: "blotztask-ui"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        working-directory: ./blotztask-ui
        run: |
          npm install
          npm run build
          mv ./build/static ./build/standalone/build
          mv ./public ./build/standalone

      - name: Install dependencies
        run: npm install
        working-directory: ./blotztask-ui

      - name: Build Next.js App (standalone)
        working-directory: ./blotztask-ui
        run: |
          npm run build
          mv ./build/static ./build/standalone/.next
          [ -d public ] && mv public build/standalone

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: wapp-blotztask-ui-staging
          publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
          package: ./blotztask-ui/build/standalone